# Generated by Django 4.1 on 2022-10-28 18:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, null=True, verbose_name='tconst')),
                ('title_type', models.CharField(choices=[('short', 'Short'), ('movie', 'Movie')], max_length=255, verbose_name='titleType')),
                ('name', models.CharField(max_length=255, verbose_name='primaryTitle')),
                ('is_adult', models.BooleanField(verbose_name='isAdult')),
                ('year', models.IntegerField(null=True, verbose_name='startYear')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255, null=True, verbose_name='nconst')),
                ('name', models.CharField(max_length=255, verbose_name='primaryName')),
                ('birth_year', models.DateField(null=True, verbose_name='birthYear')),
                ('death_year', models.DateField(null=True, verbose_name='deathYear')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='ordering')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='category')),
                ('job', models.CharField(max_length=255, null=True, verbose_name='job')),
                ('characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='Characters')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imdb.person')),
            ],
        ),
    ]
